// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Link field in *Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type NowDocumentDataSlicesSlice =
  | SliderSlice
  | LineSlice
  | ImageSlice
  | EmbedSlice
  | ColumnsSlice
  | RichTextSlice;

/**
 * Content for Now documents
 */
interface NowDocumentData {
  /**
   * Title field in *Now*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: now.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Date field in *Now*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: now.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Time field in *Now*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: now.time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField;

  /**
   * Location field in *Now*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: now.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Image field in *Now*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: now.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Now*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: now.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NowDocumentDataSlicesSlice>; /**
   * Meta Title field in *Now*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: now.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Now*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: now.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Now*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: now.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Now document from Prismic
 *
 * - **API ID**: `now`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NowDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NowDocumentData>, "now", Lang>;

type PageDocumentDataSlicesSlice =
  | SliderSlice
  | LineSlice
  | ImageSlice
  | ColumnsSlice
  | EmbedSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProgramDocumentDataSlicesSlice =
  | SliderSlice
  | LineSlice
  | ImageSlice
  | ColumnsSlice
  | EmbedSlice
  | RichTextSlice;

/**
 * Content for Program documents
 */
interface ProgramDocumentData {
  /**
   * Title field in *Program*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Program*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Image field in *Program*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: program.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Program*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: program.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProgramDocumentDataSlicesSlice>; /**
   * Meta Title field in *Program*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: program.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Program*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: program.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Program*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: program.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Program document from Prismic
 *
 * - **API ID**: `program`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProgramDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProgramDocumentData>,
    "program",
    Lang
  >;

type ResidentDocumentDataSlicesSlice =
  | SliderSlice
  | LineSlice
  | ImageSlice
  | EmbedSlice
  | ColumnsSlice
  | RichTextSlice;

/**
 * Content for Person documents
 */
interface ResidentDocumentData {
  /**
   * Name field in *Person*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resident.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Text field in *Person*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resident.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Image field in *Person*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: resident.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Person*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: resident.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ResidentDocumentDataSlicesSlice>; /**
   * Meta Title field in *Person*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: resident.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Person*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: resident.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Person*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: resident.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Person document from Prismic
 *
 * - **API ID**: `resident`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResidentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ResidentDocumentData>,
    "resident",
    Lang
  >;

export type AllDocumentTypes =
  | MenuDocument
  | NowDocument
  | PageDocument
  | ProgramDocument
  | ResidentDocument;

/**
 * Item in *Columns → Default → Primary → Column*
 */
export interface ColumnsSliceDefaultPrimaryColumnItem {
  /**
   * Content field in *Columns → Default → Primary → Column*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: columns.default.primary.column[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *Columns → Default → Primary*
 */
export interface ColumnsSliceDefaultPrimary {
  /**
   * Column field in *Columns → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: columns.default.primary.column[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  column: prismic.GroupField<Simplify<ColumnsSliceDefaultPrimaryColumnItem>>;
}

/**
 * Default variation for Columns Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ColumnsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ColumnsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Columns*
 */
type ColumnsSliceVariation = ColumnsSliceDefault;

/**
 * Columns Shared Slice
 *
 * - **API ID**: `columns`
 * - **Description**: Columns
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ColumnsSlice = prismic.SharedSlice<
  "columns",
  ColumnsSliceVariation
>;

/**
 * Primary content in *Embed → Default → Primary*
 */
export interface EmbedSliceDefaultPrimary {
  /**
   * Embed field in *Embed → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: embed.default.primary.embed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  embed: prismic.EmbedField;
}

/**
 * Default variation for Embed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EmbedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EmbedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Embed*
 */
type EmbedSliceVariation = EmbedSliceDefault;

/**
 * Embed Shared Slice
 *
 * - **API ID**: `embed`
 * - **Description**: Embed
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EmbedSlice = prismic.SharedSlice<"embed", EmbedSliceVariation>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Image → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *Line → Default → Primary*
 */
export interface LineSliceDefaultPrimary {
  /**
   * Line field in *Line → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: line.default.primary.line
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  line: prismic.BooleanField;
}

/**
 * Default variation for Line Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LineSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Line*
 */
type LineSliceVariation = LineSliceDefault;

/**
 * Line Shared Slice
 *
 * - **API ID**: `line`
 * - **Description**: Line
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LineSlice = prismic.SharedSlice<"line", LineSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Title field in *RichText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *Slider → Default → Primary → Image*
 */
export interface SliderSliceDefaultPrimaryImageItem {
  /**
   * Image field in *Slider → Default → Primary → Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.image[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Slider → Default → Primary*
 */
export interface SliderSliceDefaultPrimary {
  /**
   * Image field in *Slider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.image[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  image: prismic.GroupField<Simplify<SliderSliceDefaultPrimaryImageItem>>;
}

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      MenuDocument,
      MenuDocumentData,
      NowDocument,
      NowDocumentData,
      NowDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProgramDocument,
      ProgramDocumentData,
      ProgramDocumentDataSlicesSlice,
      ResidentDocument,
      ResidentDocumentData,
      ResidentDocumentDataSlicesSlice,
      AllDocumentTypes,
      ColumnsSlice,
      ColumnsSliceDefaultPrimaryColumnItem,
      ColumnsSliceDefaultPrimary,
      ColumnsSliceVariation,
      ColumnsSliceDefault,
      EmbedSlice,
      EmbedSliceDefaultPrimary,
      EmbedSliceVariation,
      EmbedSliceDefault,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      LineSlice,
      LineSliceDefaultPrimary,
      LineSliceVariation,
      LineSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SliderSlice,
      SliderSliceDefaultPrimaryImageItem,
      SliderSliceDefaultPrimary,
      SliderSliceVariation,
      SliderSliceDefault,
    };
  }
}
